# Credits to Professor Wang's ML Lab

In [1]:
# import data
from datetime import datetime
begin = datetime.now()
import pandas as pd
import numpy as np
data = pd.read_csv('0test-ready.csv')#sg-transport-1115-clean.csv')#sgtransport1145.csv')

# check data
print(data.shape)
data.head(10)

(2210, 4)


Sentiment  Sentiment Num  Multi  \
0   Neutral              0      0   
1  Positive              1      1   
2  Positive              1      2   
3   Neutral              0      0   
4  Positive              1      2   
5  Positive              1      1   
6  Positive              1      1   
7  Positive              1      1   
8  Positive              1      1   
9  Positive              1      2   

                                                Text  
0                 Effective  but   too-tepid  biopic  
1   If   you   sometimes   like   to    go   to  ...  
2     Emerges   as   something  rare  ,    an   i...  
3   The  film     provides   some   great  insigh...  
4   Offers    that   rare  combination   of    en...  
5  Perhaps     no  picture   ever  made     has  ...  
6     Steers   turns   in    a   snappy  screenpl...  
7           But   he   somehow     pulls  it  off  .  
8    Take  Care   of   My  Cat    offers    a    ...  
9  This      is    a  film  well  worth       see...

In [2]:
# basic pre-processing
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(review):
    review = " ".join([stemmer.stem(w.lower()) for w in word_tokenize(re.sub('[^a-zA-Z]+', ' ', review.replace("<br />", ""))) if not w in stop_words])
    return review

data['review_clean'] = data.apply(lambda x: preprocess(x['Text']), axis=1)

In [3]:
data.head(10)

Sentiment  Sentiment Num  Multi  \
0   Neutral              0      0   
1  Positive              1      1   
2  Positive              1      2   
3   Neutral              0      0   
4  Positive              1      2   
5  Positive              1      1   
6  Positive              1      1   
7  Positive              1      1   
8  Positive              1      1   
9  Positive              1      2   

                                                Text  \
0                 Effective  but   too-tepid  biopic   
1   If   you   sometimes   like   to    go   to  ...   
2     Emerges   as   something  rare  ,    an   i...   
3   The  film     provides   some   great  insigh...   
4   Offers    that   rare  combination   of    en...   
5  Perhaps     no  picture   ever  made     has  ...   
6     Steers   turns   in    a   snappy  screenpl...   
7           But   he   somehow     pulls  it  off  .   
8    Take  Care   of   My  Cat    offers    a    ...   
9  This      is    a  film  well  worth       see...   

                                        review_clean  
0                                effect tepid biopic  
1  if sometim like go movi fun wasabi good place ...  
2  emerg someth rare issu movi honest keenli obse...  
3  the film provid great insight neurot mindset c...  
4                   offer rare combin entertain educ  
5  perhap pictur ever made liter show road hell p...  
6  steer turn snappi screenplay curl edg clever w...  
7                                   but somehow pull  
8  take care my cat offer refreshingli differ sli...  
9             thi film well worth see talk sing head

### Split dataset to training and test dataset

In [4]:
# split dataset to training and test dataset
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split


data_train, data_test, y_train, y_test = train_test_split(data['review_clean'], data['Sentiment'], 
                                                          test_size = 0.25, random_state = 2020, stratify = data['Sentiment'])

vectorizer = CountVectorizer()
train_counts = vectorizer.fit_transform(data_train)
test_counts = vectorizer.transform(data_test)

### Model Fitting
### Logistic Regression

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score


lr = LogisticRegression()

lr.fit(train_counts, y_train)
lr_pred = lr.predict(test_counts)
print('Logistic Regression')
print('Accuracy:')
print(lr.score(test_counts, y_test))
print('Confusion Matrix:')
print(confusion_matrix(lr_pred, y_test))
print('F1 Score:')
print(f1_score(y_test, lr_pred, average='weighted'))


Logistic Regression
Accuracy:
0.5479204339963833
Confusion Matrix:
[[148  52  60]
 [ 21   2  15]
 [ 59  43 153]]
F1 Score:
0.5164852821161507


### Model Fitting
### Naive Bayes

In [6]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(train_counts, y_train)
nb_pred = nb.predict(test_counts)
print('Naive Bayes')
print('Accuracy:')
print(nb.score(test_counts, y_test))
print('Confusion Matrix:')
print(confusion_matrix(nb_pred, y_test))
print('F1 Score:')
print(f1_score(y_test, nb_pred, average='weighted'))

Naive Bayes
Accuracy:
0.5750452079566004
Confusion Matrix:
[[149  47  54]
 [ 11   2   7]
 [ 68  48 167]]
F1 Score:
0.5325206854314228


 ### Model Fitting - SVM
### Linear Support Vector Classification

In [7]:
from sklearn.svm import LinearSVC

start=datetime.now()
svm = LinearSVC()

svm.fit(train_counts, y_train)
svm_pred = svm.predict(test_counts)
print('SVM')
print('Accuracy:')
print(svm.score(test_counts, y_test))
print('Confusion Matrix:')
print(confusion_matrix(svm_pred, y_test))
print('F1 Score:')
print(f1_score(y_test, svm_pred, average='weighted'))

SVM
Accuracy:
0.5334538878842676
Confusion Matrix:
[[130  46  48]
 [ 42  16  31]
 [ 56  35 149]]
F1 Score:
0.5298699849916347


In [8]:
train_counts.shape

(1657, 4934)